[General]
dns-server = 223.5.5.5, 223.6.6.6, 1.1.1.1
dns-direct = 223.5.5.5
dns-fake-ip = false
dns-direct-fallback-proxy = false
dns-direct-fallback = true
ipv6 = false
skip-proxy = 192.168.0.0/16, 10.0.0.0/8, 172.16.0.0/12, localhost, *.local, 127.0.0.1
tun = false
# 推荐开启 UDP（游戏/视频更好）
udp = true

[Rule]
# ==================== 2. 特定域名 ====================
DOMAIN,dog.ssrdog.com,PROXY

# ==================== 3. 局域网与本地回路 ====================
DOMAIN-SUFFIX,local,DIRECT
IP-CIDR,10.0.0.0/8,DIRECT,no-resolve
IP-CIDR,172.16.0.0/12,DIRECT,no-resolve
IP-CIDR,192.168.0.0/16,DIRECT,no-resolve
IP-CIDR,127.0.0.0/8,DIRECT,no-resolve


# ==================== 7. 全球与中国分流 ====================
RULE-SET,https://fastly.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/direct.txt,DIRECT
RULE-SET,https://fastly.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/cncidr.txt,DIRECT,no-resolve
RULE-SET,https://raw.githubusercontent.com/Niuzheju/clash_config/refs/heads/master/white_list.list,DIRECT
# RULE-SET,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Shadowrocket/Telegram/Telegram.list,PROXY
# RULE-SET,https://raw.githubusercontent.com/Niuzheju/clash_config/refs/heads/master/xxx_content.list,PROXY
# RULE-SET,https://fastly.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/gfw.txt,PROXY

# ==================== 8. 兜底规则 ====================
GEOIP,CN,DIRECT
FINAL,PROXY

[Host]
# 可选：强制 DNS 解析
localhost = 127.0.0.1